version: '2'
services:
  php56:
    container_name: php56-fpm
    ports:
      - 9001:9000
    image: iordachej/php56-fpm
    environment:
      SERVER_NAME: localserver.juristoffice.lh
      MYSQL_SOCKET: /tmp/mysql.sock
      MYSQLI_SOCKET: /tmp/mysql.sock
    volumes:
      - phpdata:/Users/alexjorj/yp/localserver.juristoffice.ro
    networks:
      - localnet

volumes:
  phpdata:
    driver: local
    driver_opts:
      type: none
      device: $PWD/../
      o: bind

networks:
    localnet:
        external: true
#docker network create localnet
