version: '2'
services:
  php56:
    container_name: php56-fpm
    ports:
      - 9001:9000
    image: iordachej/docker-php56-fpm-debian8:latest
    environment:
      SERVER_NAME: localserver.lh
    volumes:
      - phpdata:$PWD/
      - ./php-fpm.ini:/etc/php5/fpm/php.ini
      - ./php-cli.ini:/etc/php5/cli/php.ini
    networks:
      - localnet

volumes:
  phpdata:
    driver: local
    driver_opts:
      type: none
      device: $PWD/../
      o: bind

networks:
    localnet:
        external: true
#docker network create localnet
